mpc/urls.py
from django.urls import path
from mpc import views

app_name='mpc'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('publicacao/<str:coDemandante>/secao/<str:secao>/', views.publicacao, name='publicacao'),
    path('save_publicacao/', views.save_publicacao, name='save_publicacao'),
    path('delete_publicacao/', views.delete_publicacao, name='delete_publicacao'),
    path('autocomplete_jurisdicionada/', views.autocomplete_jurisdicionada, name='autocomplete_jurisdicionada'),
    path('search_info_jurisdicionada/', views.search_info_jurisdicionada, name='search_info_jurisdicionada'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mpc/', include('mpc.urls')),
    path('user/', include('user.urls'))

]

mpc/models.py
from django.db import models

class Unidade(models.Model):
    class Meta:
        managed = False
        db_table = 'unidade'

    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50)
    sigla = models.CharField(max_length=3)
    titular = models.CharField(max_length=80)
    email = models.CharField(max_length=80)
    ramal = models.CharField(max_length=15)

    def __str__(self):
        return self.nome


class Jurisdicionada(models.Model):
    class Meta:
        managed = False
        db_table = 'jurisdicionada'

    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=255)
    coDemandante = models.CharField(max_length=255, unique=True)
    sigla = models.CharField(max_length=20)
    unidade = models.ForeignKey(Unidade, on_delete=models.CASCADE)
    apelido = models.CharField(max_length=50)
    vl_bens_serv = models.DecimalField(max_digits=12, decimal_places=2)
    vl_obras_eng = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return self.nome


class Demandante(models.Model):
    class Meta:
        managed = False
        db_table = 'demandante'
    id = models.AutoField(primary_key=True)
    coDemandante = models.CharField(max_length=255, unique=True)
    coDemandantePai = models.CharField(max_length=255)
    nome = models.CharField(max_length=255)

    def __str__(self):
        return self.coDemandante


class DodfPublicacao(models.Model):
    class Meta:
        managed = False
        db_table = 'dodfPublicacao'  # Nome da tabela no banco de dados

    id = models.AutoField(primary_key=True)
    coMateria = models.CharField(max_length=255)
    coDemandante = models.CharField(max_length=255)
    secao = models.CharField(max_length=10)
    titulo = models.CharField(max_length=255)
    preambulo = models.TextField()  # Use TextField para campos NVARCHAR(MAX)
    tipo = models.CharField(max_length=255)
    situacao = models.CharField(max_length=255)
    regraSituacao = models.CharField(max_length=255)
    layout = models.CharField(max_length=255)
    nuOrdem = models.CharField(max_length=255)
    texto = models.TextField()  # Use TextField para campos NVARCHAR(MAX)
    carga = models.DateTimeField()

    def __str__(self) -> str:
        return f'{self.coDemandante}: -> {self.titulo}'


class PublicacaoAnalisada(models.Model):
    class Meta:
        db_table = 'publicacao_analisada'
    
    user = models.ForeignKey('user.UserProfile', null=True, on_delete=models.SET_NULL)
    dodf = models.OneToOneField(DodfPublicacao, null=True, on_delete=models.SET_NULL)
    comentario=models.TextField(null=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

mpc/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import render
from .models import *
from user.models import UserProfile
from django.contrib.auth.decorators import login_required
import json
from datetime import datetime
from .service import  publicacao_por_demandante, get_analise_by_dodf_id
from .cache import get_cached_jurisdicionadas_with_descendentes
from django.db.models import Q, OuterRef, Subquery
from django.core.paginator import Paginator, EmptyPage

def get_publicacoes_by_day(coDemandantes, data, secao=['I', 'III']):
    dic = {}

    for coDemandante in coDemandantes:
        descendentes = get_cached_jurisdicionadas_with_descendentes(
            coDemandante
        )
        publicacoes = publicacao_por_demandante(descendentes, secao, data)
        dic[coDemandante] = publicacoes

    return dic


def convert_data_publicacao(data_publicacao):
    if data_publicacao:
        data = datetime.strptime(data_publicacao, "%Y-%m-%d").date()
    else:
        data = datetime.now().date()

    return data

@login_required(login_url='user:login', redirect_field_name='next')
def dashboard(request):
    data_publicacao = request.GET.get('data_publicacao')
    current_date = datetime.now().date()
    data = convert_data_publicacao(data_publicacao)

    user_profile = UserProfile.objects.prefetch_related('jurisdicionadas').get(user=request.user)
    jurisdicionadas = user_profile.jurisdicionadas.all()
    coDemandantes = jurisdicionadas.filter(~Q(coDemandante='')).values_list('coDemandante', flat=True)
    
    dic = get_publicacoes_by_day(coDemandantes, data)
    
    return render(request, 'pages/dashboard.html', {
        'jurisdicionadas': jurisdicionadas,
        'unidade': user_profile.unidades,
        'info': dic,
        'data': data_publicacao,
        'data_atual': f'{current_date.year}-{current_date.month}-{current_date.day}'
    })


@login_required(login_url='user:login')
def publicacao(request, coDemandante, secao):
    data_publicacao = request.GET.get('data_publicacao')
    current_date = datetime.now().date()
    data = convert_data_publicacao(data_publicacao)

    user_profile = UserProfile.objects.prefetch_related('jurisdicionadas').get(user=request.user)
    jurisdicionadas = user_profile.jurisdicionadas.all() 
    coDemandantes = jurisdicionadas.filter(~Q(coDemandante='')).values_list('coDemandante', flat=True)
    
    dic = get_publicacoes_by_day(coDemandantes, data, [secao])
    current_jurisdicionada = [jurisdicionada for jurisdicionada in jurisdicionadas if jurisdicionada.coDemandante==coDemandante][0]
    
    publicacoes = dic[coDemandante]
    return render(request, 'pages/publicacao.html', {
        'noticias': publicacoes,
        'secao': secao,
        'jurisdicionada': current_jurisdicionada,
        'publicacao_cadastrada': {},
        'data': data_publicacao,
        'data_atual': f'{current_date.year}-{current_date.month}-{current_date.day}'
    })


@login_required(login_url='user:login')
def save_publicacao(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        publicacao_id = data.get('noticia_id')
        comentario = data.get('comentario')

        publicacao_analisada = get_analise_by_dodf_id(publicacao_id)

        if (not publicacao_analisada):
            publicacao_analisada = PublicacaoAnalisada.objects.create(
                user = UserProfile.objects.get(user=request.user),
                dodf_id=publicacao_id,
                comentario=comentario,
            )
            publicacao_analisada.save()
        else:
            publicacao_analisada.comentario = comentario
            publicacao_analisada.save()
        
            
        return JsonResponse({'status': 'success', 'message': 'Comentário salvo com sucesso!'})

@login_required(login_url='user:login')
def delete_publicacao(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        publicacao_id = data.get('noticia_id')
        publicacao = get_analise_by_dodf_id(publicacao_id)
        if not publicacao:
            raise Http404("Publicação não encontrada!")
        publicacao.delete()
        return JsonResponse({'status': 'success', 'message': 'Comentário apagado com sucesso!'})
    
@login_required(login_url='user:login')
def autocomplete_jurisdicionada(request):
    term = request.GET.get('term')  # Termo digitado pelo usuário
    jurisdicionadas = Jurisdicionada.objects.filter(nome__icontains=term)[:10]  # Filtra as jurisdicionadas que contêm o termo
    results = [{'label': jurisdicionada.nome, 'value': jurisdicionada.id} for jurisdicionada in jurisdicionadas]
    return JsonResponse(results, safe=False)


@login_required(login_url='user:login')
def search_info_jurisdicionada(request):
    search = request.GET.get('q')
    jurisdicionada_id=request.GET.get('jurisdicionada_id')
    jurisdicionada = None
    if jurisdicionada_id:
        jurisdicionada = Jurisdicionada.objects.get(pk=jurisdicionada_id)
        demandantes = get_cached_jurisdicionadas_with_descendentes(jurisdicionada.coDemandante)
    
    
    data_publicacao = request.GET.get('data_publicacao')
    data = convert_data_publicacao(data_publicacao)
    nome_subquery = Demandante.objects.filter(
        coDemandante=OuterRef('coDemandante')
    ).values('nome')[:1]

    query = Q(~Q(secao='II'), Q(titulo__contains=search) | Q(texto__contains=search), carga__date=data)

    if jurisdicionada_id:
        query &= Q(coDemandante__in=demandantes)

    publicacoes_list = DodfPublicacao.objects.annotate(
        nome_demandante=Subquery(nome_subquery)
    ).select_related('publicacaoanalisada').filter(query).order_by('carga')

    paginator = Paginator(publicacoes_list, 10)  
    page = request.GET.get('page', 1)
    
    try:
        publicacoes = paginator.page(page)
    except EmptyPage:
        publicacoes = paginator.page(paginator.num_pages)
    return render(request, 'pages/search-publicacoes.html', {
        'page_results': publicacoes, 
        'current_page': publicacoes.number, 
        'total_pages': paginator.num_pages, 
        'has_previous': publicacoes.has_previous(), 
        'has_next': publicacoes.has_next(),
        'search': search,
        'data': data,
        'data_publicacao': data_publicacao,
        'jurisdicionada': jurisdicionada,
        })

mpc/templates/pages/dashboard.html
{% extends "template/global.html" %} 
{% load custom_tags %}
{% load static %}
{% block title %}
Dashboard
{% endblock %}

{% block content %} 

<style>
  .hover-shadow:hover {
    box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
  }

  /* Estilo customizado para hover nas linhas da tabela */
  .custom-table tbody tr:hover {
    background-color: #f2f2f2;
  }
  
  /* Estilo para remover bordas entre colunas */
  .custom-table thead th, .custom-table tbody td {
    border-left: none;
    border-right: none;
  }
  
  /* Padding extra nas células para uma sensação espaçosa */
  .custom-table th, .custom-table td {
    padding: 20px 10px;
  }
  
  /* Estilo para bordas arredondadas na tabela */
  .custom-table-container {
    border: 1px solid #dee2e6;
    border-radius: .25rem;
    overflow: hidden;
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1); /* Adiciona sombra à tabela */
  }

  .container-rounded {
    background-color: white;
    border-radius: 10px;
    padding: 20px;
    margin-bottom: 20px;
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1); /* Adiciona sombra ao container */
  }

  .square-box {
    background-color: white;
    border-radius: 10px;
    padding: 10px;
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2); /* Adiciona sombra ao quadrado */
    transition: transform 0.3s ease-in-out; /* Adiciona transição de hover */
  }

  .square-box:hover {
    box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
  }

  .date-format {
    font-size: 1.2rem;
  }

  #jurisdicionada-input {
    width: 300px; /* Largura limitada */
    padding: 10px;
    font-size: 16px;
    border-radius: 10px;
    transition: border-color 0.3s ease-in-out;
    margin-bottom: 15px; /* Espaçamento inferior */
  }

  /* Estilo para mudar a cor da borda quando o input estiver focado */
  #jurisdicionada-input:focus {
    outline: none;
    border-color: #007bff;
  }

  /* Estilo para os itens do autocompletar usando Bootstrap */
  .ui-autocomplete {
    max-height: 200px;
    overflow-y: auto;
    overflow-x: hidden;
    z-index: 1000;
  }

  /* Estilo para cada item do autocompletar */
  .ui-menu-item {
    padding: 10px;
    cursor: pointer;
  }

  /* Estilo quando um item do autocompletar estiver focado */
  .ui-state-focus {
    background-color: #007bff;
    color: white;
  }

  /* Estilo do badge para jurisdicionada selecionada */
.jurisdicionada-badge {
    display: inline-block;
    padding: 5px 10px;
    border-radius: 15px;
    background-color: #333;
    color: white;
    margin-top: 10px; /* Espaço acima do badge */
    position: relative;
}

/* Estilo do botão 'x' para fechar/remover o badge */
.jurisdicionada-badge .close-badge {
    background-color: #555;
    border-radius: 50%;
    position: absolute;
    right: -5px;
    top: -5px;
    width: 16px;
    height: 16px;
    line-height: 16px;
    text-align: center;
    cursor: pointer;
    font-size: 12px;
}


  
</style>
  <div class="container my-4 container-rounded">
    <div class="row">
      <div class="col-lg-12">
        <div class="square-box mb-3 d-flex justify-content-around">
          <h1 class="display-5">
            Jurisdicionadas
          </h1>
          <h1 class="display-5">
            {% if data %}
              {{ data|get_formated_data }}
            {% else %}
              {{ data_atual|get_formated_data }}
            {% endif %}
          </h1>
        </div>
      </div>
    </div>
    <!-- Formulário começa aqui -->
    <form action="{% url 'mpc:search_info_jurisdicionada' %}" method="GET">
        <div class="input-group">
          <!-- Dropdown de Jurisdicionada -->
          <div class="dropdown me-2"> <!-- me-2 é uma classe do Bootstrap para dar margem à direita -->
              <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                  Selecione Jurisdicionada
              </button>
              <div class="dropdown-menu p-4">
                  <div class="mb-3">
                      <label for="jurisdicionada-input" class="form-label">Jurisdicionada</label>
                      <input type="text" id="jurisdicionada-input" placeholder="Digite o nome da jurisdicionada" class="form-control">
                  </div>
              </div>
              
          </div>
          
          <!-- Input de busca -->
          <input type="text" class="form-control me-2" placeholder="Buscar..." name="q"> <!-- me-2 é uma classe do Bootstrap para dar margem à direita -->
          
          <!-- Botão de busca -->
          <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="submit">Buscar</button>
          </div>
        </div>
        <!-- Container do badge da jurisdicionada selecionada -->
        <div class="selected-jurisdicionada"></div>
        {% if data %}
        <input type="hidden" name="data_publicacao" value="{{ data }}">
        {% endif %}
        <input type="hidden" id="jurisdicionada-id" name="jurisdicionada_id" value="">
    </form>
    
    

    <div class="row mt-3">
      <div class="col-lg-6 mb-4 d-flex align-items-stretch">
        <div class="p-4 bg-white rounded shadow hover-shadow flex-grow-1">
          <h4 class="mb-4">Informações do Usuário</h4>
          <div class="d-flex justify-content-between">
            <div class="info-item">
              <strong>Assessor:</strong>
              <p class="text-muted">{{ request.user.username|capfirst }}</p>
            </div>
            <div class="info-item">
              <strong>Unidade:</strong>
              <p class="text-muted">{{ unidade }}</p>
            </div>
          </div>
        </div>
      </div>
    

      <div class="col-lg-6 mb-4 d-flex align-items-stretch">
        <!-- Seção de Busca por Datas -->
        <div class="p-3 bg-white rounded shadow hover-shadow flex-grow-1">
          <h4 class="mb-3">Buscar por Datas</h4>
          <form method="get" class="row">
            <div class="col-sm-8">
              <input type="date" {% if data %}value="{{ data }}" {% endif %} name="data_publicacao" class="form-control">
            </div>
            <div class="col-sm-4">
              <button type="submit" class="btn btn-primary">Buscar</button>
              <a href="{% url 'mpc:dashboard' %}" class="btn btn-success">Hoje</a>
            </div>
          </form>
        </div>
      </div>
    </div>

  <!-- Tabela de Jurisdicionadas -->
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive custom-table-container">
      <table class="table table-hover custom-table mb-0">
        <thead class="bg-primary text-white">
          <tr>
            <th scope="col">Identificador</th>
            <th scope="col">Nome</th>
            <th scope="col">Sigla</th>
            <th scope="col">Seção I</th>
            <th scope="col">Seção III</th>
          </tr>
        </thead>
        <tbody>
          {% for jurisdicionada in jurisdicionadas %}
          <tr>
            <td> 
              {% if jurisdicionada.coDemandante %}
                {{jurisdicionada.coDemandante}}
              {% endif %} </td>
            <td>         
                {{jurisdicionada.nome}}
            </td>
            <td>{{jurisdicionada.sigla|default:'-'}}</td>
            <td>

              {% if info|get_item:jurisdicionada.coDemandante|get_item_by_secao:'I'|length > 0 %}
                <a class="text-primary text-decoration-none" href="{% url 'mpc:publicacao' coDemandante=jurisdicionada.coDemandante secao='I' %}{% if data %}?data_publicacao={{ data }}{% endif %}">
                  {{ info|get_item:jurisdicionada.coDemandante|get_item_by_secao:'I'|length }} Publicação <i class="fa-solid fa-arrow-right-from-bracket"></i>
                </a>
              {% else %}
                0 Publicação
              {% endif %}

            </td>
            <td>
              <ul>
                {% if info|get_item:jurisdicionada.coDemandante|get_item_by_secao:'III'|length > 0 %}
                  <a class="text-primary text-decoration-none" href="{% url 'mpc:publicacao' coDemandante=jurisdicionada.coDemandante secao='III' %}{% if data %}?data_publicacao={{ data }}{% endif %}">
                    {{ info|get_item:jurisdicionada.coDemandante|get_item_by_secao:'III'|length }} Publicação <i class="fa-solid fa-arrow-right-from-bracket"></i>
                  </a>
                {% else %}
                0 Publicação
                {% endif %}
              </ul>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

<script>
  $(function() {
    $("#jurisdicionada-input").autocomplete({
        source: "{% url 'mpc:autocomplete_jurisdicionada' %}",
        minLength: 2, // Número mínimo de caracteres para acionar o autocompletar
        select: function(event, ui) {
          $("#jurisdicionada-input").val("");  // Limpa o campo de texto após a seleção
          $("#jurisdicionada-id").val(ui.item.value);

          // Cria o badge da jurisdicionada selecionada
          var badgeHTML = `<div class="jurisdicionada-badge">
                              ${ui.item.label}
                              <span class="close-badge" onclick="removeJurisdicionadaBadge()">×</span>
                           </div>`;
          $(".selected-jurisdicionada").html(badgeHTML);
          return false;
      }
    });
  });
  
  // Função para remover o badge quando o 'x' for clicado
  function removeJurisdicionadaBadge() {
    $(".selected-jurisdicionada").empty();
    $("#jurisdicionada-id").val("");
  }

  </script>
  


{% endblock %}

mpc/templates/pages/search-publicacoes.html
{% extends "template/global.html" %}
{% load custom_tags %}

{% block title %}
Publicações
{% endblock %}

{% block content %}
<style>
    /* Estilo para a paginação */
    .pagination {
      display: flex;
      justify-content: center;
      align-items: center;
      margin-top: 20px;
    }
  
    /* Estilo para os links de página */
    .page-link {
      color: #007bff;
    }
  
    /* Estilo para o link de página ativa */
    .page-item.active .page-link {
      background-color: #007bff;
      border-color: #007bff;
    }

    
  .container-rounded {
    background-color: white;
    border-radius: 10px;
    padding: 20px;
    margin-bottom: 20px;
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1); /* Adiciona sombra ao container */
  }

    #jurisdicionada-input {
      width: 300px; /* Largura limitada */
      padding: 10px;
      font-size: 16px;
      border-radius: 10px;
      transition: border-color 0.3s ease-in-out;
      margin-bottom: 15px; /* Espaçamento inferior */
    }
  
    /* Estilo para mudar a cor da borda quando o input estiver focado */
    #jurisdicionada-input:focus {
      outline: none;
      border-color: #007bff;
    }
  
    /* Estilo para os itens do autocompletar usando Bootstrap */
    .ui-autocomplete {
      max-height: 200px;
      overflow-y: auto;
      overflow-x: hidden;
      z-index: 1000;
    }
  
    /* Estilo para cada item do autocompletar */
    .ui-menu-item {
      padding: 10px;
      cursor: pointer;
    }
  
    /* Estilo quando um item do autocompletar estiver focado */
    .ui-state-focus {
      background-color: #007bff;
      color: white;
    }
  
    /* Estilo do badge para jurisdicionada selecionada */
  .jurisdicionada-badge {
      display: inline-block;
      padding: 5px 10px;
      border-radius: 15px;
      background-color: #333;
      color: white;
      margin-top: 10px; /* Espaço acima do badge */
      position: relative;
  }
  
  /* Estilo do botão 'x' para fechar/remover o badge */
  .jurisdicionada-badge .close-badge {
      background-color: #555;
      border-radius: 50%;
      position: absolute;
      right: -5px;
      top: -5px;
      width: 16px;
      height: 16px;
      line-height: 16px;
      text-align: center;
      cursor: pointer;
      font-size: 12px;
  }
  </style>
  
  <div class="row container-rounded">
    <!-- Título Atualizado -->
    <div class="card mb-4 bg-dark text-white shadow">
      <div class="card-body d-flex justify-content-between align-items-center">
          <div class="d-flex flex-column align-items-center">
              <h4 class="mb-0">Publicações</h4>
              <p class="mb-0">Data: {{data|date:"d/m/Y"}}</p>
          </div>
          <div class="d-flex flex-column align-items-center">
              <h4 class="mb-0">Pesquisa</h4>
              <p class="mb-0">{{search}}</p>
          </div>
      </div>
    </div>

    <!-- Formulário começa aqui -->
    <form class="mb-4" action="{% url 'mpc:search_info_jurisdicionada' %}" method="GET">
        <div class="input-group">
          <!-- Dropdown de Jurisdicionada -->
          <div class="dropdown me-2"> <!-- me-2 é uma classe do Bootstrap para dar margem à direita -->
              <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                  Selecione Jurisdicionada
              </button>
              <div class="dropdown-menu p-4">
                  <div class="mb-3">
                      <label for="jurisdicionada-input" class="form-label">Jurisdicionada</label>
                      <input type="text" id="jurisdicionada-input" placeholder="Digite o nome da jurisdicionada" class="form-control">
                  </div>
              </div>
              
          </div>
          
          <!-- Input de busca -->
          <input type="text" class="form-control me-2" placeholder="Buscar..." name="q"> <!-- me-2 é uma classe do Bootstrap para dar margem à direita -->
          
          <!-- Botão de busca -->
          <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="submit">Buscar</button>
          </div>
        </div>
        <!-- Container do badge da jurisdicionada selecionada -->
        <div class="selected-jurisdicionada">
          {% if jurisdicionada %}
            <div class="jurisdicionada-badge">
              {{jurisdicionada}}
              <span class="close-badge" onclick="removeJurisdicionadaBadge()">×</span>
          </div>
          {% endif %}
        </div>
        {% if data_publicacao %}
          <input type="hidden" name="data_publicacao" value="{{ data_publicacao }}">
        {% endif %}
        {% if jurisdicionada %}
          <input type="hidden" id="jurisdicionada-id" name="jurisdicionada_id" value="{{jurisdicionada.id}}">
          {% else %}  
          <input type="hidden" id="jurisdicionada-id" name="jurisdicionada_id" value="">
        {% endif %}
    </form>

    {% for publicacao in page_results %}
    <div class="card mb-4">
      <div class="card-body">
        <h7 class="card-title d-flex align-items-center justify-content-around">          
          <div class="d-flex flex-column align-items-center justify-content-center"> 
            <h6>{{ publicacao.nome_demandante }}</h6>
            <p class="">Seção {{publicacao.secao}}  -  {{publicacao.carga|date:"d/m/Y"}}</p>
          </div>
          <button class="btn btn-link text-decoration-none btn-toggle" data-publicacao-id="{{ publicacao.id }}">
              {{ publicacao.titulo|safe }} <i class="fa-solid fa-arrow-turn-down"></i>
          </button>
          
        </h7>
        <div class="card-content d-none">
          <p class="card-text">{{ publicacao.texto|safe }}</p>
          <div class="form-group">
            <label for="comentario-{{ noticia.id }}">Comentário:</label>
            <textarea class="form-control" id="comentario-{{ noticia.id }}" rows="3" disabled>{% if publicacao.publicacaoanalisada.comentario %}{{publicacao.publicacaoanalisada.comentario}}{% endif %}</textarea>
          </div>
          <button class="btn btn-danger btn-delete mt-3" data-publicacao-id="{{ publicacao.id }}">Ocultar</button>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>

</div>
  
  <!-- Adicione os links de página gerados automaticamente pelo Paginator -->
  <div class="pagination">
    <span class="step-links">
      {% if has_previous %}
        <a href="?q={{search}}&page=1{% if data_publicacao  %}&data_publicacao={{data_publicacao}}{% endif %}">&laquo; first</a>
        <a href="?q={{search}}&page={{ current_page|add:"-1" }}{% if data_publicacao  %}&data_publicacao={{data_publicacao}}{% endif %}">previous</a>
      {% endif %}
  
      <span class="current">
        Página {{ current_page }} de {{ total_pages }}.
      </span>
  
      {% if has_next %}
        <a href="?q={{search}}&page={{ current_page|add:"1" }}{% if data_publicacao %}&data_publicacao={{data_publicacao}}{% endif %}">next</a>
        <a href="?q={{search}}&page={{ total_pages }}{% if data_publicacao  %}&data_publicacao={{data_publicacao}}{% endif %}">last &raquo;</a>
      {% endif %}
    </span>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function () {
    const toggleButtons = document.querySelectorAll('.btn-toggle');
    const hideButtons = document.querySelectorAll('.btn-delete');
  
    toggleButtons.forEach((button) => {
      button.addEventListener('click', function () {
        const noticiaId = button.getAttribute('data-noticia-id');
        const cardContent = button.parentElement.nextElementSibling;
        cardContent.classList.toggle('d-none');
      });
    });
  
    hideButtons.forEach((button) => {
      button.addEventListener('click', function () {
        const noticiaId = button.getAttribute('data-noticia-id');
        const cardContent = button.parentElement;
        cardContent.classList.add('d-none');
      });
    });
  });

  $(function() {
    $("#jurisdicionada-input").autocomplete({
        source: "{% url 'mpc:autocomplete_jurisdicionada' %}",
        minLength: 2, // Número mínimo de caracteres para acionar o autocompletar
        select: function(event, ui) {
          $("#jurisdicionada-input").val("");  // Limpa o campo de texto após a seleção
          $("#jurisdicionada-id").val(ui.item.value);

          // Cria o badge da jurisdicionada selecionada
          var badgeHTML = `<div class="jurisdicionada-badge">
                              ${ui.item.label}
                              <span class="close-badge" onclick="removeJurisdicionadaBadge()">×</span>
                           </div>`;
          $(".selected-jurisdicionada").html(badgeHTML);
          return false;
      }
    });
  });
  
  // Função para remover o badge quando o 'x' for clicado
  function removeJurisdicionadaBadge() {
    $(".selected-jurisdicionada").empty();
    $("#jurisdicionada-id").val("");
  }
  
</script>
  {% endblock %}